apiVersion: v1
kind: Secret
metadata:
    name: mediawiki-r2
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:/jvMKbJB9yPVDgbddzUy,iv:+jsaBEQHv9sELfWskKt7M+FO4dfMD6eYNkDVz4by6PA=,tag:E0of6PVdKOsktVcObS3coA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:CmWmdtUhVc3nvcxD/J9dSYzvFxDMHcwU7V+UHsIiR4Q=,iv:jV2LIEXNHi/8jMLsyXWujbgZ/RcHndNg8AnMxOVAtDc=,tag:tYigTirQ48UYKTTGOB8oJg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:gk2Qgc5YTQhyO8sRInEIhG/sEqj+awKpYspYjWx4A4j/NQWanabmxKA9DDRtsHTYyX1Hm6pJk/2YHUsywYQbZQ==,iv:u2XrpElJSMKQEdBR9ghA2B7lulGiJrZNepuKSucrj/I=,tag:bOkMRcXoaCecvnJqxuDXmQ==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:wWB44g==,iv:ZU7kH7OgQWRUxxpkGjxNMHcBo1S3YvM08kVTh6k0KQ0=,tag:HescGhPjAkerYNhElBCKWA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    gcp_kms:
        - created_at: "2026-09-19T13:48:27Z"
          enc: CiQAXZOUpQt9VYrXJ//NVnXoxdKHB6ocD79TfP6yDV0Molidi8gSSQCGHyGMB6O9/uM9Rzl+j+I8zcZeu530V1vUveExoo2mqB8MruxNvdRPxwW3sOc3yyMZd90hz+j2NzRVYsTUHr8Sxj9rqwQcXo0=
          resource_id: projects/raya-dns/locations/europe-west4/keyRings/raya-sops/cryptoKeys/sops
    lastmodified: "2026-09-19T18:19:34Z"
    mac: ENC[AES256_GCM,data:a4ZUiBqAaLQGlAewOlgI8wOQvweu/cz9m6A2zPblwlcWU6N9Sz0PZXuEB8BkZBIeQwKH+qP48NInVSvMg9sHpQrMX/Gj/sYmtQdegtatZ1/dhM6lfDHbhIYxtXTez0qZZLWhblwcXXn/Nqy22QY+/XZDRwKmd1lkw0AZNZQXP1A=,iv:CZ42y3TULD7Jzf4ixK6o9P5hDiPnlDZwkwXlkdQVgx0=,tag:USa5OK59SVkuDvgAuRlUWA==,type:str]
    version: 3.13.3
