apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mw.name" . }}-uploads
  annotations:
    helm.sh/resource-policy: keep
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: hcloud-volumes
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
